PRICES_AS_OF = "May 2026"

STOCKS = [
    {
        "name": "Apple",
        "ticker": "AAPL",
        "sector": "Technology",
        "price": 210,
        "hint": "$100 – $500",
        "fact": "Apple was the first US company to hit a $3 trillion market cap.",
    },
    {
        "name": "NVIDIA",
        "ticker": "NVDA",
        "sector": "Semiconductors",
        "price": 130,
        "hint": "$100 – $500",
        "fact": "NVIDIA's GPUs power most of the world's AI model training.",
    },
    {
        "name": "Tesla",
        "ticker": "TSLA",
        "sector": "Electric Vehicles",
        "price": 426,
        "hint": "$100 – $500",
        "fact": "Tesla delivers over 1.8 million vehicles per year globally.",
    },
    {
        "name": "Amazon",
        "ticker": "AMZN",
        "sector": "E-Commerce / Cloud",
        "price": 220,
        "hint": "$100 – $500",
        "fact": "Amazon Web Services generates more profit than the entire retail business.",
    },
    {
        "name": "Microsoft",
        "ticker": "MSFT",
        "sector": "Technology",
        "price": 430,
        "hint": "$100 – $500",
        "fact": "Microsoft invested $13 billion into OpenAI, the company behind ChatGPT.",
    },
    {
        "name": "Meta",
        "ticker": "META",
        "sector": "Social Media",
        "price": 590,
        "hint": "$500 – $1000",
        "fact": "Meta's apps reach over 3 billion daily users.",
    },
    {
        "name": "Netflix",
        "ticker": "NFLX",
        "sector": "Streaming",
        "price": 1100,
        "hint": "$500+",
        "fact": "Netflix has over 300 million paid subscribers across 190 countries.",
    },
    {
        "name": "Google",
        "ticker": "GOOGL",
        "sector": "Technology",
        "price": 170,
        "hint": "$100 – $500",
        "fact": "Google processes over 8.5 billion searches per day.",
    },
    {
        "name": "Palantir",
        "ticker": "PLTR",
        "sector": "AI / Defense",
        "price": 120,
        "hint": "Under $200",
        "fact": "Palantir's AI platform is used by the US Army and dozens of intelligence agencies.",
    },
    {
        "name": "Spotify",
        "ticker": "SPOT",
        "sector": "Music Streaming",
        "price": 640,
        "hint": "$500 – $1000",
        "fact": "Spotify has over 600 million monthly active users.",
    },
    {
        "name": "AMD",
        "ticker": "AMD",
        "sector": "Semiconductors",
        "price": 110,
        "hint": "Under $200",
        "fact": "AMD's EPYC chips now power a significant share of major cloud data centers.",
    },
    {
        "name": "Coinbase",
        "ticker": "COIN",
        "sector": "Crypto Exchange",
        "price": 240,
        "hint": "$100 – $500",
        "fact": "Coinbase is the largest regulated crypto exchange in the United States.",
    },
    {
        "name": "Occidental Petroleum",
        "ticker": "OXY",
        "sector": "Oil",
        "price": 58.81,
        "hint": "$25 – $100",
        "fact": "Berkshire Hathaway owns over 25% of Occidental Petroleum.",
    },
    {
        "name": "Schwab US Dividend Equity ETF",
        "ticker": "SCHD",
        "sector": "ETF General",
        "price": 32.83,
        "hint": "$25 – $50",
        "fact": "SCHD tracks high-dividend US stocks and is one of the most popular income ETFs.",
    },
    {
        "name": "Schwab US Broad Market ETF",
        "ticker": "SCHB",
        "sector": "Heavy General",
        "price": 28.73,
        "hint": "$20 – $50",
        "fact": "SCHB covers nearly the entire US stock market with over 2,500 holdings.",
    },
    {
        "name": "SPDR Gold MiniShares",
        "ticker": "GLDM",
        "sector": "Gold",
        "price": 89.21,
        "hint": "$50 – $150",
        "fact": "GLDM offers low-cost exposure to gold bullion with each share backed by physical gold.",
    },
    {
        "name": "Navitas Semiconductor",
        "ticker": "NVTS",
        "sector": "Semiconductors",
        "price": 20.00,
        "hint": "Under $50",
        "fact": "Navitas makes GaN power ICs used in fast chargers for phones and laptops.",
    },
    {
        "name": "Berkshire Hathaway B",
        "ticker": "BRK-B",
        "sector": "Diversified",
        "price": 486.38,
        "hint": "$400 – $600",
        "fact": "Berkshire Hathaway B shares let everyday investors own a piece of Warren Buffett's conglomerate.",
    },
    {
        "name": "Realty Income",
        "ticker": "O",
        "sector": "REIT",
        "price": 62.03,
        "hint": "$40 – $100",
        "fact": "Realty Income pays monthly dividends and has increased them for over 25 consecutive years.",
    },
]

SECTOR_GOAL_MAP = {
    "Technology":        ["ai", "tech", "growth"],
    "Semiconductors":    ["ai", "tech", "growth"],
    "AI / Defense":      ["ai", "tech"],
    "Streaming":         ["streaming", "entertainment", "growth"],
    "Music Streaming":   ["streaming", "entertainment"],
    "Social Media":      ["tech", "growth", "social"],
    "Electric Vehicles": ["growth", "green", "innovation"],
    "E-Commerce / Cloud":["tech", "growth", "cloud"],
    "Crypto Exchange":   ["crypto", "alternative", "growth"],
}

TIERS = ["S+", "S", "A", "B", "C", "D", "F"]

TIER_STYLES = {
    "S+": "bold green",
    "S":  "green",
    "A":  "bold cyan",
    "B":  "cyan",
    "C":  "bold yellow",
    "D":  "yellow",
    "F":  "bold red",
}
